apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-k8s-1
  annotations:
    kubernetes.io/change-cause: "update image from latest to v2"
  labels:
    app: hello-k8s-1
spec:
  selector:
    matchLabels:
      app: hello-k8s-1
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-k8s-1
    spec:
      containers:
        - name: hello-k8s-1
          image: thanhnb1/hello-k8s:v2
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 100m
              memory: 500Mi
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-k8s-1
spec:
  selector:
    app: hello-k8s-1
  type: ClusterIP
  ports:
  - name: hello-k8s-1
    protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-k8s-2
  annotations:
    kubernetes.io/change-cause: "update image from latest to v2"
  labels:
    app: hello-k8s-2
spec:
  selector:
    matchLabels:
      app: hello-k8s-2
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-k8s-2
    spec:
      containers:
        - name: hello-k8s-2
          image: thanhnb1/hello-k8s:v2
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 100m
              memory: 500Mi
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-k8s-2
spec:
  selector:
    app: hello-k8s-2
  type: ClusterIP
  ports:
  - name: hello-k8s-2
    protocol: TCP
    port: 80
    targetPort: 8080