apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: hello-k8s
  labels:
    app: hello-k8s
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: env
        operator: In
        values:
          - develop
          - staging
  template:
    metadata:
      labels:
        app: hello-k8s
        env: develop
    spec:
      containers:
      - name: hello-k8s
        image: thanhnb1/hello-k8s:latest
        ports:
        - containerPort: 8080